#!/usr/bin/env ruby

puts "# Generated by `../generators/syntax/percent_generator.rb > percent.rb`\n\n"

%Q[~`!@\#$%^&*_-+=|:;',.?/].split(//).each do |s|
  puts <<-END.gsub(/^\s{4}/, '')
    %#{s}
      foo
      \\#{s}
      \\\\\\#{s}
      bar
    #{s}


  END
end

puts "#\svim:foldmethod=syntax"

# vim:foldmethod=syntax
