# Generated by `./etc/examples/generators/syntax/percent_generator.rb __END__ > etc/examples/syntax/percent/__END__.rb`

  __END__
  invalid
  invalid


__END__
  valid
  valid


# vim:foldmethod=syntax
