# Generated by `./etc/examples/generators/syntax/percent_generator.rb comment > etc/examples/syntax/percent/comment.rb`

  # foo
  # foo
    # bar

  baz



=begin foo bar
  comment
=end baz


# vim:foldmethod=syntax
