# Generated by `./etc/examples/generators/syntax/percent_generator.rb def > etc/examples/syntax/percent/def.rb`

def
  foo
  def
    bar
  end
end


class
  foo
end


module
  foo
end


# vim:foldmethod=syntax
