# Generated by `./etc/examples/generators/syntax/percent_generator.rb %i > etc/examples/syntax/percent/i.rb`

  %i~
    foo
    \~
    \\\~
    bar
  ~


  %i`
    foo
    \`
    \\\`
    bar
  `


  %i!
    foo
    \!
    \\\!
    bar
  !


  %i@
    foo
    \@
    \\\@
    bar
  @


  %i#
    foo
    \#
    \\\#
    bar
  #


  %i$
    foo
    \$
    \\\$
    bar
  $


  %i%
    foo
    \%
    \\\%
    bar
  %


  %i^
    foo
    \^
    \\\^
    bar
  ^


  %i&
    foo
    \&
    \\\&
    bar
  &


  %i*
    foo
    \*
    \\\*
    bar
  *


  %i_
    foo
    \_
    \\\_
    bar
  _


  %i-
    foo
    \-
    \\\-
    bar
  -


  %i+
    foo
    \+
    \\\+
    bar
  +


  %i=
    foo
    \=
    \\\=
    bar
  =


  %i|
    foo
    \|
    \\\|
    bar
  |


  %i:
    foo
    \:
    \\\:
    bar
  :


  %i;
    foo
    \;
    \\\;
    bar
  ;


  %i"
    foo
    \"
    \\\"
    bar
  "


  %i'
    foo
    \'
    \\\'
    bar
  '


  %i,
    foo
    \,
    \\\,
    bar
  ,


  %i.
    foo
    \.
    \\\.
    bar
  .


  %i?
    foo
    \?
    \\\?
    bar
  ?


  %i/
    foo
    \/
    \\\/
    bar
  /


  %i{
    foo
    \}
    \\\}
    bar
  }


  %i<
    foo
    \>
    \\\>
    bar
  >


  %i[
    foo
    \]
    \\\]
    bar
  ]


  %i(
    foo
    \)
    \\\)
    bar
  )


  %I~
    foo
    \~
    \\\~
    bar
  ~


  %I`
    foo
    \`
    \\\`
    bar
  `


  %I!
    foo
    \!
    \\\!
    bar
  !


  %I@
    foo
    \@
    \\\@
    bar
  @


  %I#
    foo
    \#
    \\\#
    bar
  #


  %I$
    foo
    \$
    \\\$
    bar
  $


  %I%
    foo
    \%
    \\\%
    bar
  %


  %I^
    foo
    \^
    \\\^
    bar
  ^


  %I&
    foo
    \&
    \\\&
    bar
  &


  %I*
    foo
    \*
    \\\*
    bar
  *


  %I_
    foo
    \_
    \\\_
    bar
  _


  %I-
    foo
    \-
    \\\-
    bar
  -


  %I+
    foo
    \+
    \\\+
    bar
  +


  %I=
    foo
    \=
    \\\=
    bar
  =


  %I|
    foo
    \|
    \\\|
    bar
  |


  %I:
    foo
    \:
    \\\:
    bar
  :


  %I;
    foo
    \;
    \\\;
    bar
  ;


  %I"
    foo
    \"
    \\\"
    bar
  "


  %I'
    foo
    \'
    \\\'
    bar
  '


  %I,
    foo
    \,
    \\\,
    bar
  ,


  %I.
    foo
    \.
    \\\.
    bar
  .


  %I?
    foo
    \?
    \\\?
    bar
  ?


  %I/
    foo
    \/
    \\\/
    bar
  /


  %I{
    foo
    \}
    \\\}
    bar
  }


  %I<
    foo
    \>
    \\\>
    bar
  >


  %I[
    foo
    \]
    \\\]
    bar
  ]


  %I(
    foo
    \)
    \\\)
    bar
  )


# vim:foldmethod=syntax
