# Generated by `./etc/examples/generators/syntax/percent_generator.rb if > etc/examples/syntax/percent/if.rb`

if 1
  foo
else
  bar
end

foo \
  if 1
    foo
  else
    bar
  end

baz ...= if 1
  foo
else
  bar
end


42foo? if 1
  bar
else
  baz
end


42foo! if 1
  bar
else
  baz
end


foo { if 1
  bar
else
  baz
end


foo : if 1
  bar
else
  baz
end


foo , if 1
  bar
else
  baz
end


foo ; if 1
  bar
else
  baz
end


foo ( if 1
  bar
else
  baz
end


foo [ if 1
  bar
else
  baz
end


foo < if 1
  bar
else
  baz
end


foo > if 1
  bar
else
  baz
end


foo ~ if 1
  bar
else
  baz
end


foo \ if 1
  bar
else
  baz
end


foo * if 1
  bar
else
  baz
end


foo % if 1
  bar
else
  baz
end


foo & if 1
  bar
else
  baz
end


foo ^ if 1
  bar
else
  baz
end


foo | if 1
  bar
else
  baz
end


foo + if 1
  bar
else
  baz
end


foo = if 1
  bar
else
  baz
end


foo - if 1
  bar
else
  baz
end


if 1
  (1..5).end
  :: end
end

if 1
..end


not_BOF if 1
  bar
else
  baz
end


_foo? if 1
  bar
else
  baz
end


_foo! if 1
  bar
else
  baz
end


unless 1
  foo
else
  bar
end

foo \
  unless 1
    foo
  else
    bar
  end

baz ...= unless 1
  foo
else
  bar
end


42foo? unless 1
  bar
else
  baz
end


42foo! unless 1
  bar
else
  baz
end


foo { unless 1
  bar
else
  baz
end


foo : unless 1
  bar
else
  baz
end


foo , unless 1
  bar
else
  baz
end


foo ; unless 1
  bar
else
  baz
end


foo ( unless 1
  bar
else
  baz
end


foo [ unless 1
  bar
else
  baz
end


foo < unless 1
  bar
else
  baz
end


foo > unless 1
  bar
else
  baz
end


foo ~ unless 1
  bar
else
  baz
end


foo \ unless 1
  bar
else
  baz
end


foo * unless 1
  bar
else
  baz
end


foo % unless 1
  bar
else
  baz
end


foo & unless 1
  bar
else
  baz
end


foo ^ unless 1
  bar
else
  baz
end


foo | unless 1
  bar
else
  baz
end


foo + unless 1
  bar
else
  baz
end


foo = unless 1
  bar
else
  baz
end


foo - unless 1
  bar
else
  baz
end


unless 1
  (1..5).end
  :: end
end

unless 1
..end


not_BOF unless 1
  bar
else
  baz
end


_foo? unless 1
  bar
else
  baz
end


_foo! unless 1
  bar
else
  baz
end


# vim:foldmethod=syntax
