# Generated by `./etc/examples/generators/syntax/percent_generator.rb regexp > etc/examples/syntax/percent/regexp.rb`


# Begin test for option '' {{{

    /
      foo
      \/
      \\\/
      bar
    /


  and/
    foo
    \/
    \\\/
    bar
  /


  or/
    foo
    \/
    \\\/
    bar
  /


  while/
    foo
    \/
    \\\/
    bar
  /


  until/
    foo
    \/
    \\\/
    bar
  /


  unless/
    foo
    \/
    \\\/
    bar
  /


  if/
    foo
    \/
    \\\/
    bar
  /


  elsif/
    foo
    \/
    \\\/
    bar
  /


  when/
    foo
    \/
    \\\/
    bar
  /


  not/
    foo
    \/
    \\\/
    bar
  /


  then/
    foo
    \/
    \\\/
    bar
  /


  else/
    foo
    \/
    \\\/
    bar
  /


  ;/
    foo
    \/
    \\\/
    bar
  /


   ~/
    foo
    \/
    \\\/
    bar
  /


  =/
    foo
    \/
    \\\/
    bar
  /


  !/
    foo
    \/
    \\\/
    bar
  /


  |/
    foo
    \/
    \\\/
    bar
  /


  (/
    foo
    \/
    \\\/
    bar
  /


  &/
    foo
    \/
    \\\/
    bar
  /


  ,/
    foo
    \/
    \\\/
    bar
  /


  {/
    foo
    \/
    \\\/
    bar
  /


  [/
    foo
    \/
    \\\/
    bar
  /


  </
    foo
    \/
    \\\/
    bar
  /


  >/
    foo
    \/
    \\\/
    bar
  /


  ?/
    foo
    \/
    \\\/
    bar
  /


  :/
    foo
    \/
    \\\/
    bar
  /


  */
    foo
    \/
    \\\/
    bar
  /


  +/
    foo
    \/
    \\\/
    bar
  /


  -/
    foo
    \/
    \\\/
    bar
  /


  _foo  / 
    foo
    \/
    \\\/
    bar
  /


  _foo  /	
    foo
    \/
    \\\/
    bar
  /


  _foo  /=
    foo
    \/
    \\\/
    bar
  /


  _foo  /OK
    foo
    \/
    \\\/
    bar
  /


# }}} End test for option ''

# Begin test for option 'i' {{{

    /
      foo
      \/
      \\\/
      bar
    /i


  and/
    foo
    \/
    \\\/
    bar
  /i


  or/
    foo
    \/
    \\\/
    bar
  /i


  while/
    foo
    \/
    \\\/
    bar
  /i


  until/
    foo
    \/
    \\\/
    bar
  /i


  unless/
    foo
    \/
    \\\/
    bar
  /i


  if/
    foo
    \/
    \\\/
    bar
  /i


  elsif/
    foo
    \/
    \\\/
    bar
  /i


  when/
    foo
    \/
    \\\/
    bar
  /i


  not/
    foo
    \/
    \\\/
    bar
  /i


  then/
    foo
    \/
    \\\/
    bar
  /i


  else/
    foo
    \/
    \\\/
    bar
  /i


  ;/
    foo
    \/
    \\\/
    bar
  /i


   ~/
    foo
    \/
    \\\/
    bar
  /i


  =/
    foo
    \/
    \\\/
    bar
  /i


  !/
    foo
    \/
    \\\/
    bar
  /i


  |/
    foo
    \/
    \\\/
    bar
  /i


  (/
    foo
    \/
    \\\/
    bar
  /i


  &/
    foo
    \/
    \\\/
    bar
  /i


  ,/
    foo
    \/
    \\\/
    bar
  /i


  {/
    foo
    \/
    \\\/
    bar
  /i


  [/
    foo
    \/
    \\\/
    bar
  /i


  </
    foo
    \/
    \\\/
    bar
  /i


  >/
    foo
    \/
    \\\/
    bar
  /i


  ?/
    foo
    \/
    \\\/
    bar
  /i


  :/
    foo
    \/
    \\\/
    bar
  /i


  */
    foo
    \/
    \\\/
    bar
  /i


  +/
    foo
    \/
    \\\/
    bar
  /i


  -/
    foo
    \/
    \\\/
    bar
  /i


  _foo  / 
    foo
    \/
    \\\/
    bar
  /i


  _foo  /	
    foo
    \/
    \\\/
    bar
  /i


  _foo  /=
    foo
    \/
    \\\/
    bar
  /i


  _foo  /OK
    foo
    \/
    \\\/
    bar
  /i


# }}} End test for option 'i'

# Begin test for option 'o' {{{

    /
      foo
      \/
      \\\/
      bar
    /o


  and/
    foo
    \/
    \\\/
    bar
  /o


  or/
    foo
    \/
    \\\/
    bar
  /o


  while/
    foo
    \/
    \\\/
    bar
  /o


  until/
    foo
    \/
    \\\/
    bar
  /o


  unless/
    foo
    \/
    \\\/
    bar
  /o


  if/
    foo
    \/
    \\\/
    bar
  /o


  elsif/
    foo
    \/
    \\\/
    bar
  /o


  when/
    foo
    \/
    \\\/
    bar
  /o


  not/
    foo
    \/
    \\\/
    bar
  /o


  then/
    foo
    \/
    \\\/
    bar
  /o


  else/
    foo
    \/
    \\\/
    bar
  /o


  ;/
    foo
    \/
    \\\/
    bar
  /o


   ~/
    foo
    \/
    \\\/
    bar
  /o


  =/
    foo
    \/
    \\\/
    bar
  /o


  !/
    foo
    \/
    \\\/
    bar
  /o


  |/
    foo
    \/
    \\\/
    bar
  /o


  (/
    foo
    \/
    \\\/
    bar
  /o


  &/
    foo
    \/
    \\\/
    bar
  /o


  ,/
    foo
    \/
    \\\/
    bar
  /o


  {/
    foo
    \/
    \\\/
    bar
  /o


  [/
    foo
    \/
    \\\/
    bar
  /o


  </
    foo
    \/
    \\\/
    bar
  /o


  >/
    foo
    \/
    \\\/
    bar
  /o


  ?/
    foo
    \/
    \\\/
    bar
  /o


  :/
    foo
    \/
    \\\/
    bar
  /o


  */
    foo
    \/
    \\\/
    bar
  /o


  +/
    foo
    \/
    \\\/
    bar
  /o


  -/
    foo
    \/
    \\\/
    bar
  /o


  _foo  / 
    foo
    \/
    \\\/
    bar
  /o


  _foo  /	
    foo
    \/
    \\\/
    bar
  /o


  _foo  /=
    foo
    \/
    \\\/
    bar
  /o


  _foo  /OK
    foo
    \/
    \\\/
    bar
  /o


# }}} End test for option 'o'

# Begin test for option 'm' {{{

    /
      foo
      \/
      \\\/
      bar
    /m


  and/
    foo
    \/
    \\\/
    bar
  /m


  or/
    foo
    \/
    \\\/
    bar
  /m


  while/
    foo
    \/
    \\\/
    bar
  /m


  until/
    foo
    \/
    \\\/
    bar
  /m


  unless/
    foo
    \/
    \\\/
    bar
  /m


  if/
    foo
    \/
    \\\/
    bar
  /m


  elsif/
    foo
    \/
    \\\/
    bar
  /m


  when/
    foo
    \/
    \\\/
    bar
  /m


  not/
    foo
    \/
    \\\/
    bar
  /m


  then/
    foo
    \/
    \\\/
    bar
  /m


  else/
    foo
    \/
    \\\/
    bar
  /m


  ;/
    foo
    \/
    \\\/
    bar
  /m


   ~/
    foo
    \/
    \\\/
    bar
  /m


  =/
    foo
    \/
    \\\/
    bar
  /m


  !/
    foo
    \/
    \\\/
    bar
  /m


  |/
    foo
    \/
    \\\/
    bar
  /m


  (/
    foo
    \/
    \\\/
    bar
  /m


  &/
    foo
    \/
    \\\/
    bar
  /m


  ,/
    foo
    \/
    \\\/
    bar
  /m


  {/
    foo
    \/
    \\\/
    bar
  /m


  [/
    foo
    \/
    \\\/
    bar
  /m


  </
    foo
    \/
    \\\/
    bar
  /m


  >/
    foo
    \/
    \\\/
    bar
  /m


  ?/
    foo
    \/
    \\\/
    bar
  /m


  :/
    foo
    \/
    \\\/
    bar
  /m


  */
    foo
    \/
    \\\/
    bar
  /m


  +/
    foo
    \/
    \\\/
    bar
  /m


  -/
    foo
    \/
    \\\/
    bar
  /m


  _foo  / 
    foo
    \/
    \\\/
    bar
  /m


  _foo  /	
    foo
    \/
    \\\/
    bar
  /m


  _foo  /=
    foo
    \/
    \\\/
    bar
  /m


  _foo  /OK
    foo
    \/
    \\\/
    bar
  /m


# }}} End test for option 'm'

# Begin test for option 'x' {{{

    /
      foo
      \/
      \\\/
      bar
    /x


  and/
    foo
    \/
    \\\/
    bar
  /x


  or/
    foo
    \/
    \\\/
    bar
  /x


  while/
    foo
    \/
    \\\/
    bar
  /x


  until/
    foo
    \/
    \\\/
    bar
  /x


  unless/
    foo
    \/
    \\\/
    bar
  /x


  if/
    foo
    \/
    \\\/
    bar
  /x


  elsif/
    foo
    \/
    \\\/
    bar
  /x


  when/
    foo
    \/
    \\\/
    bar
  /x


  not/
    foo
    \/
    \\\/
    bar
  /x


  then/
    foo
    \/
    \\\/
    bar
  /x


  else/
    foo
    \/
    \\\/
    bar
  /x


  ;/
    foo
    \/
    \\\/
    bar
  /x


   ~/
    foo
    \/
    \\\/
    bar
  /x


  =/
    foo
    \/
    \\\/
    bar
  /x


  !/
    foo
    \/
    \\\/
    bar
  /x


  |/
    foo
    \/
    \\\/
    bar
  /x


  (/
    foo
    \/
    \\\/
    bar
  /x


  &/
    foo
    \/
    \\\/
    bar
  /x


  ,/
    foo
    \/
    \\\/
    bar
  /x


  {/
    foo
    \/
    \\\/
    bar
  /x


  [/
    foo
    \/
    \\\/
    bar
  /x


  </
    foo
    \/
    \\\/
    bar
  /x


  >/
    foo
    \/
    \\\/
    bar
  /x


  ?/
    foo
    \/
    \\\/
    bar
  /x


  :/
    foo
    \/
    \\\/
    bar
  /x


  */
    foo
    \/
    \\\/
    bar
  /x


  +/
    foo
    \/
    \\\/
    bar
  /x


  -/
    foo
    \/
    \\\/
    bar
  /x


  _foo  / 
    foo
    \/
    \\\/
    bar
  /x


  _foo  /	
    foo
    \/
    \\\/
    bar
  /x


  _foo  /=
    foo
    \/
    \\\/
    bar
  /x


  _foo  /OK
    foo
    \/
    \\\/
    bar
  /x


# }}} End test for option 'x'

# Begin test for option 'n' {{{

    /
      foo
      \/
      \\\/
      bar
    /n


  and/
    foo
    \/
    \\\/
    bar
  /n


  or/
    foo
    \/
    \\\/
    bar
  /n


  while/
    foo
    \/
    \\\/
    bar
  /n


  until/
    foo
    \/
    \\\/
    bar
  /n


  unless/
    foo
    \/
    \\\/
    bar
  /n


  if/
    foo
    \/
    \\\/
    bar
  /n


  elsif/
    foo
    \/
    \\\/
    bar
  /n


  when/
    foo
    \/
    \\\/
    bar
  /n


  not/
    foo
    \/
    \\\/
    bar
  /n


  then/
    foo
    \/
    \\\/
    bar
  /n


  else/
    foo
    \/
    \\\/
    bar
  /n


  ;/
    foo
    \/
    \\\/
    bar
  /n


   ~/
    foo
    \/
    \\\/
    bar
  /n


  =/
    foo
    \/
    \\\/
    bar
  /n


  !/
    foo
    \/
    \\\/
    bar
  /n


  |/
    foo
    \/
    \\\/
    bar
  /n


  (/
    foo
    \/
    \\\/
    bar
  /n


  &/
    foo
    \/
    \\\/
    bar
  /n


  ,/
    foo
    \/
    \\\/
    bar
  /n


  {/
    foo
    \/
    \\\/
    bar
  /n


  [/
    foo
    \/
    \\\/
    bar
  /n


  </
    foo
    \/
    \\\/
    bar
  /n


  >/
    foo
    \/
    \\\/
    bar
  /n


  ?/
    foo
    \/
    \\\/
    bar
  /n


  :/
    foo
    \/
    \\\/
    bar
  /n


  */
    foo
    \/
    \\\/
    bar
  /n


  +/
    foo
    \/
    \\\/
    bar
  /n


  -/
    foo
    \/
    \\\/
    bar
  /n


  _foo  / 
    foo
    \/
    \\\/
    bar
  /n


  _foo  /	
    foo
    \/
    \\\/
    bar
  /n


  _foo  /=
    foo
    \/
    \\\/
    bar
  /n


  _foo  /OK
    foo
    \/
    \\\/
    bar
  /n


# }}} End test for option 'n'

# Begin test for option 'e' {{{

    /
      foo
      \/
      \\\/
      bar
    /e


  and/
    foo
    \/
    \\\/
    bar
  /e


  or/
    foo
    \/
    \\\/
    bar
  /e


  while/
    foo
    \/
    \\\/
    bar
  /e


  until/
    foo
    \/
    \\\/
    bar
  /e


  unless/
    foo
    \/
    \\\/
    bar
  /e


  if/
    foo
    \/
    \\\/
    bar
  /e


  elsif/
    foo
    \/
    \\\/
    bar
  /e


  when/
    foo
    \/
    \\\/
    bar
  /e


  not/
    foo
    \/
    \\\/
    bar
  /e


  then/
    foo
    \/
    \\\/
    bar
  /e


  else/
    foo
    \/
    \\\/
    bar
  /e


  ;/
    foo
    \/
    \\\/
    bar
  /e


   ~/
    foo
    \/
    \\\/
    bar
  /e


  =/
    foo
    \/
    \\\/
    bar
  /e


  !/
    foo
    \/
    \\\/
    bar
  /e


  |/
    foo
    \/
    \\\/
    bar
  /e


  (/
    foo
    \/
    \\\/
    bar
  /e


  &/
    foo
    \/
    \\\/
    bar
  /e


  ,/
    foo
    \/
    \\\/
    bar
  /e


  {/
    foo
    \/
    \\\/
    bar
  /e


  [/
    foo
    \/
    \\\/
    bar
  /e


  </
    foo
    \/
    \\\/
    bar
  /e


  >/
    foo
    \/
    \\\/
    bar
  /e


  ?/
    foo
    \/
    \\\/
    bar
  /e


  :/
    foo
    \/
    \\\/
    bar
  /e


  */
    foo
    \/
    \\\/
    bar
  /e


  +/
    foo
    \/
    \\\/
    bar
  /e


  -/
    foo
    \/
    \\\/
    bar
  /e


  _foo  / 
    foo
    \/
    \\\/
    bar
  /e


  _foo  /	
    foo
    \/
    \\\/
    bar
  /e


  _foo  /=
    foo
    \/
    \\\/
    bar
  /e


  _foo  /OK
    foo
    \/
    \\\/
    bar
  /e


# }}} End test for option 'e'

# Begin test for option 'u' {{{

    /
      foo
      \/
      \\\/
      bar
    /u


  and/
    foo
    \/
    \\\/
    bar
  /u


  or/
    foo
    \/
    \\\/
    bar
  /u


  while/
    foo
    \/
    \\\/
    bar
  /u


  until/
    foo
    \/
    \\\/
    bar
  /u


  unless/
    foo
    \/
    \\\/
    bar
  /u


  if/
    foo
    \/
    \\\/
    bar
  /u


  elsif/
    foo
    \/
    \\\/
    bar
  /u


  when/
    foo
    \/
    \\\/
    bar
  /u


  not/
    foo
    \/
    \\\/
    bar
  /u


  then/
    foo
    \/
    \\\/
    bar
  /u


  else/
    foo
    \/
    \\\/
    bar
  /u


  ;/
    foo
    \/
    \\\/
    bar
  /u


   ~/
    foo
    \/
    \\\/
    bar
  /u


  =/
    foo
    \/
    \\\/
    bar
  /u


  !/
    foo
    \/
    \\\/
    bar
  /u


  |/
    foo
    \/
    \\\/
    bar
  /u


  (/
    foo
    \/
    \\\/
    bar
  /u


  &/
    foo
    \/
    \\\/
    bar
  /u


  ,/
    foo
    \/
    \\\/
    bar
  /u


  {/
    foo
    \/
    \\\/
    bar
  /u


  [/
    foo
    \/
    \\\/
    bar
  /u


  </
    foo
    \/
    \\\/
    bar
  /u


  >/
    foo
    \/
    \\\/
    bar
  /u


  ?/
    foo
    \/
    \\\/
    bar
  /u


  :/
    foo
    \/
    \\\/
    bar
  /u


  */
    foo
    \/
    \\\/
    bar
  /u


  +/
    foo
    \/
    \\\/
    bar
  /u


  -/
    foo
    \/
    \\\/
    bar
  /u


  _foo  / 
    foo
    \/
    \\\/
    bar
  /u


  _foo  /	
    foo
    \/
    \\\/
    bar
  /u


  _foo  /=
    foo
    \/
    \\\/
    bar
  /u


  _foo  /OK
    foo
    \/
    \\\/
    bar
  /u


# }}} End test for option 'u'

# Begin test for option 's' {{{

    /
      foo
      \/
      \\\/
      bar
    /s


  and/
    foo
    \/
    \\\/
    bar
  /s


  or/
    foo
    \/
    \\\/
    bar
  /s


  while/
    foo
    \/
    \\\/
    bar
  /s


  until/
    foo
    \/
    \\\/
    bar
  /s


  unless/
    foo
    \/
    \\\/
    bar
  /s


  if/
    foo
    \/
    \\\/
    bar
  /s


  elsif/
    foo
    \/
    \\\/
    bar
  /s


  when/
    foo
    \/
    \\\/
    bar
  /s


  not/
    foo
    \/
    \\\/
    bar
  /s


  then/
    foo
    \/
    \\\/
    bar
  /s


  else/
    foo
    \/
    \\\/
    bar
  /s


  ;/
    foo
    \/
    \\\/
    bar
  /s


   ~/
    foo
    \/
    \\\/
    bar
  /s


  =/
    foo
    \/
    \\\/
    bar
  /s


  !/
    foo
    \/
    \\\/
    bar
  /s


  |/
    foo
    \/
    \\\/
    bar
  /s


  (/
    foo
    \/
    \\\/
    bar
  /s


  &/
    foo
    \/
    \\\/
    bar
  /s


  ,/
    foo
    \/
    \\\/
    bar
  /s


  {/
    foo
    \/
    \\\/
    bar
  /s


  [/
    foo
    \/
    \\\/
    bar
  /s


  </
    foo
    \/
    \\\/
    bar
  /s


  >/
    foo
    \/
    \\\/
    bar
  /s


  ?/
    foo
    \/
    \\\/
    bar
  /s


  :/
    foo
    \/
    \\\/
    bar
  /s


  */
    foo
    \/
    \\\/
    bar
  /s


  +/
    foo
    \/
    \\\/
    bar
  /s


  -/
    foo
    \/
    \\\/
    bar
  /s


  _foo  / 
    foo
    \/
    \\\/
    bar
  /s


  _foo  /	
    foo
    \/
    \\\/
    bar
  /s


  _foo  /=
    foo
    \/
    \\\/
    bar
  /s


  _foo  /OK
    foo
    \/
    \\\/
    bar
  /s


# }}} End test for option 's'

# Test for ternary operation (8c1c484) {{{

yo = 4 ? /quack#{3}/ : /quack/

# }}} End test for ternary operation
# vim:foldmethod=syntax
