# Generated by `./etc/examples/generators/syntax/percent_generator.rb string > etc/examples/syntax/percent/string.rb`

  '
    foo
    \'
    \\\'
    bar
  '


  "
    foo
    \"
    \\\"
    bar
  "


  `
    foo
    \`
    \\\`
    bar
  `


# vim:foldmethod=syntax
