# Generated by `./etc/examples/generators/syntax.rb blocks > etc/examples/syntax/blocks.rb`

def
  foo
  def
    bar
  end
end


class
  foo
end


module
  foo
end


do
  foo
end


begin
  foo
end


case
  foo
end


# vim:foldmethod=syntax
