# Generated by `./etc/examples/generators/syntax.rb brackets > etc/examples/syntax/brackets.rb`

{
  foo
}


[
  foo
]


_xxx[
  foo
]


][
  foo
]


}[
  foo
]


)[
  foo
]


# vim:foldmethod=syntax
