# Generated by `./etc/examples/generators/syntax.rb for > etc/examples/syntax/for.rb`

for 1
  foo
end


until 1
  foo
end


baz ...= until 1
  foo
end


foo { until 1
  bar
end


foo : until 1
  bar
end


foo , until 1
  bar
end


foo ; until 1
  bar
end


foo ( until 1
  bar
end


foo [ until 1
  bar
end


foo < until 1
  bar
end


foo > until 1
  bar
end


foo ~ until 1
  bar
end


foo \ until 1
  bar
end


foo * until 1
  bar
end


foo / until 1
  bar
end


foo % until 1
  bar
end


foo & until 1
  bar
end


foo ^ until 1
  bar
end


foo | until 1
  bar
end


foo + until 1
  bar
end


foo - until 1
  bar
end


not_BOF until 1
  bar
end


_foo? until 1
  bar
end


_foo! until 1
  bar
end


while 1
  foo
end


baz ...= while 1
  foo
end


foo { while 1
  bar
end


foo : while 1
  bar
end


foo , while 1
  bar
end


foo ; while 1
  bar
end


foo ( while 1
  bar
end


foo [ while 1
  bar
end


foo < while 1
  bar
end


foo > while 1
  bar
end


foo ~ while 1
  bar
end


foo \ while 1
  bar
end


foo * while 1
  bar
end


foo / while 1
  bar
end


foo % while 1
  bar
end


foo & while 1
  bar
end


foo ^ while 1
  bar
end


foo | while 1
  bar
end


foo + while 1
  bar
end


foo - while 1
  bar
end


not_BOF while 1
  bar
end


_foo? while 1
  bar
end


_foo! while 1
  bar
end


# vim:foldmethod=syntax
