# Generated by `./etc/examples/generators/syntax.rb heredoc > etc/examples/syntax/heredoc.rb`


# Begin of valid cases {{{

  <<_LABEL.?!, foo
    bar baz
_LABEL

    <<-_LABEL.?!, foo
    bar baz
  _LABEL


  <<'_LABEL'.?!, foo
    bar baz
_LABEL

    <<-'_LABEL'.?!, foo
    bar baz
  _LABEL


  <<"_LABEL".?!, foo
    bar baz
_LABEL

    <<-"_LABEL".?!, foo
    bar baz
  _LABEL


  <<`_LABEL`.?!, foo
    bar baz
_LABEL

    <<-`_LABEL`.?!, foo
    bar baz
  _LABEL


# }}} End of valid cases'


# Begin of INVALID cases {{{

class
 <<LABEL
  foo
LABEL


::
 <<LABEL
  foo
LABEL


] <<LABEL
  foo
LABEL


} <<LABEL
  foo
LABEL


) <<LABEL
  foo
LABEL


" <<LABEL
  foo
LABEL
  " # close to ensure next case clean

' <<LABEL
  foo
LABEL
  ' # close to ensure next case clean

. <<LABEL
  foo
LABEL


09<<LABEL
  foo
LABEL


aZ<<LABEL
  foo
LABEL


_w<<LABEL
  foo
LABEL


<<LABEL foo<<_bar
  baz
LABEL


  <<LABEL foo<<-_bar
  baz
LABEL



<<LABEL foo<<'_bar
  baz
LABEL
  ' # close to ensure next case clean

  <<LABEL foo<<-'_bar
  baz
LABEL
  ' # close to ensure next case clean


<<LABEL foo<<"_bar
  baz
LABEL
  " # close to ensure next case clean

  <<LABEL foo<<-"_bar
  baz
LABEL
  " # close to ensure next case clean


<<LABEL foo<<`_bar
  baz
LABEL


  <<LABEL foo<<-`_bar
  baz
LABEL



# }}} End of INVALID cases'

# vim:foldmethod=syntax
