# Generated by `../generators/syntax/percent_generator.rb > percent.rb`

%~
  foo
  \~
  \\\~
  bar
~


%`
  foo
  \`
  \\\`
  bar
`


%!
  foo
  \!
  \\\!
  bar
!


%@
  foo
  \@
  \\\@
  bar
@


%#
  foo
  \#
  \\\#
  bar
#


%$
  foo
  \$
  \\\$
  bar
$


%%
  foo
  \%
  \\\%
  bar
%


%^
  foo
  \^
  \\\^
  bar
^


%&
  foo
  \&
  \\\&
  bar
&


%*
  foo
  \*
  \\\*
  bar
*


%_
  foo
  \_
  \\\_
  bar
_


%-
  foo
  \-
  \\\-
  bar
-


%+
  foo
  \+
  \\\+
  bar
+


%=
  foo
  \=
  \\\=
  bar
=


%|
  foo
  \|
  \\\|
  bar
|


%:
  foo
  \:
  \\\:
  bar
:


%;
  foo
  \;
  \\\;
  bar
;


%'
  foo
  \'
  \\\'
  bar
'


%,
  foo
  \,
  \\\,
  bar
,


%.
  foo
  \.
  \\\.
  bar
.


%?
  foo
  \?
  \\\?
  bar
?


%/
  foo
  \/
  \\\/
  bar
/


# vim:foldmethod=syntax
