# Generated by `./etc/examples/generators/syntax.rb %q > etc/examples/syntax/q.rb`

  %q~
    foo
    \~
    \\\~
    bar
  ~


  %q`
    foo
    \`
    \\\`
    bar
  `


  %q!
    foo
    \!
    \\\!
    bar
  !


  %q@
    foo
    \@
    \\\@
    bar
  @


  %q#
    foo
    \#
    \\\#
    bar
  #


  %q$
    foo
    \$
    \\\$
    bar
  $


  %q%
    foo
    \%
    \\\%
    bar
  %


  %q^
    foo
    \^
    \\\^
    bar
  ^


  %q&
    foo
    \&
    \\\&
    bar
  &


  %q*
    foo
    \*
    \\\*
    bar
  *


  %q_
    foo
    \_
    \\\_
    bar
  _


  %q-
    foo
    \-
    \\\-
    bar
  -


  %q+
    foo
    \+
    \\\+
    bar
  +


  %q=
    foo
    \=
    \\\=
    bar
  =


  %q|
    foo
    \|
    \\\|
    bar
  |


  %q:
    foo
    \:
    \\\:
    bar
  :


  %q;
    foo
    \;
    \\\;
    bar
  ;


  %q"
    foo
    \"
    \\\"
    bar
  "


  %q'
    foo
    \'
    \\\'
    bar
  '


  %q,
    foo
    \,
    \\\,
    bar
  ,


  %q.
    foo
    \.
    \\\.
    bar
  .


  %q?
    foo
    \?
    \\\?
    bar
  ?


  %q/
    foo
    \/
    \\\/
    bar
  /


  %q{
    foo
    \}
    \\\}
    bar
  }


  %q<
    foo
    \>
    \\\>
    bar
  >


  %q[
    foo
    \]
    \\\]
    bar
  ]


  %q(
    foo
    \)
    \\\)
    bar
  )


  %q foo\ \\\ bar 

  %w~
    foo
    \~
    \\\~
    bar
  ~


  %w`
    foo
    \`
    \\\`
    bar
  `


  %w!
    foo
    \!
    \\\!
    bar
  !


  %w@
    foo
    \@
    \\\@
    bar
  @


  %w#
    foo
    \#
    \\\#
    bar
  #


  %w$
    foo
    \$
    \\\$
    bar
  $


  %w%
    foo
    \%
    \\\%
    bar
  %


  %w^
    foo
    \^
    \\\^
    bar
  ^


  %w&
    foo
    \&
    \\\&
    bar
  &


  %w*
    foo
    \*
    \\\*
    bar
  *


  %w_
    foo
    \_
    \\\_
    bar
  _


  %w-
    foo
    \-
    \\\-
    bar
  -


  %w+
    foo
    \+
    \\\+
    bar
  +


  %w=
    foo
    \=
    \\\=
    bar
  =


  %w|
    foo
    \|
    \\\|
    bar
  |


  %w:
    foo
    \:
    \\\:
    bar
  :


  %w;
    foo
    \;
    \\\;
    bar
  ;


  %w"
    foo
    \"
    \\\"
    bar
  "


  %w'
    foo
    \'
    \\\'
    bar
  '


  %w,
    foo
    \,
    \\\,
    bar
  ,


  %w.
    foo
    \.
    \\\.
    bar
  .


  %w?
    foo
    \?
    \\\?
    bar
  ?


  %w/
    foo
    \/
    \\\/
    bar
  /


  %w{
    foo
    \}
    \\\}
    bar
  }


  %w<
    foo
    \>
    \\\>
    bar
  >


  %w[
    foo
    \]
    \\\]
    bar
  ]


  %w(
    foo
    \)
    \\\)
    bar
  )


  %s~
    foo
    \~
    \\\~
    bar
  ~


  %s`
    foo
    \`
    \\\`
    bar
  `


  %s!
    foo
    \!
    \\\!
    bar
  !


  %s@
    foo
    \@
    \\\@
    bar
  @


  %s#
    foo
    \#
    \\\#
    bar
  #


  %s$
    foo
    \$
    \\\$
    bar
  $


  %s%
    foo
    \%
    \\\%
    bar
  %


  %s^
    foo
    \^
    \\\^
    bar
  ^


  %s&
    foo
    \&
    \\\&
    bar
  &


  %s*
    foo
    \*
    \\\*
    bar
  *


  %s_
    foo
    \_
    \\\_
    bar
  _


  %s-
    foo
    \-
    \\\-
    bar
  -


  %s+
    foo
    \+
    \\\+
    bar
  +


  %s=
    foo
    \=
    \\\=
    bar
  =


  %s|
    foo
    \|
    \\\|
    bar
  |


  %s:
    foo
    \:
    \\\:
    bar
  :


  %s;
    foo
    \;
    \\\;
    bar
  ;


  %s"
    foo
    \"
    \\\"
    bar
  "


  %s'
    foo
    \'
    \\\'
    bar
  '


  %s,
    foo
    \,
    \\\,
    bar
  ,


  %s.
    foo
    \.
    \\\.
    bar
  .


  %s?
    foo
    \?
    \\\?
    bar
  ?


  %s/
    foo
    \/
    \\\/
    bar
  /


  %s{
    foo
    \}
    \\\}
    bar
  }


  %s<
    foo
    \>
    \\\>
    bar
  >


  %s[
    foo
    \]
    \\\]
    bar
  ]


  %s(
    foo
    \)
    \\\)
    bar
  )


# vim:foldmethod=syntax
