# Generated by `./etc/examples/generators/syntax.rb %r > etc/examples/syntax/r.rb`

  %r~
    foo
    \~
    \\\~
    bar
  ~


  %r`
    foo
    \`
    \\\`
    bar
  `


  %r!
    foo
    \!
    \\\!
    bar
  !


  %r@
    foo
    \@
    \\\@
    bar
  @


  %r#
    foo
    \#
    \\\#
    bar
  #


  %r$
    foo
    \$
    \\\$
    bar
  $


  %r%
    foo
    \%
    \\\%
    bar
  %


  %r^
    foo
    \^
    \\\^
    bar
  ^


  %r&
    foo
    \&
    \\\&
    bar
  &


  %r*
    foo
    \*
    \\\*
    bar
  *


  %r_
    foo
    \_
    \\\_
    bar
  _


  %r-
    foo
    \-
    \\\-
    bar
  -


  %r+
    foo
    \+
    \\\+
    bar
  +


  %r=
    foo
    \=
    \\\=
    bar
  =


  %r|
    foo
    \|
    \\\|
    bar
  |


  %r:
    foo
    \:
    \\\:
    bar
  :


  %r;
    foo
    \;
    \\\;
    bar
  ;


  %r"
    foo
    \"
    \\\"
    bar
  "


  %r'
    foo
    \'
    \\\'
    bar
  '


  %r,
    foo
    \,
    \\\,
    bar
  ,


  %r.
    foo
    \.
    \\\.
    bar
  .


  %r?
    foo
    \?
    \\\?
    bar
  ?


  %r/
    foo
    \/
    \\\/
    bar
  /


  %r{
    foo
    \}
    \\\}
    bar
  }


  %r<
    foo
    \>
    \\\>
    bar
  >


  %r[
    foo
    \]
    \\\]
    bar
  ]


  %r(
    foo
    \)
    \\\)
    bar
  )


# vim:foldmethod=syntax
