# Generated by `./etc/examples/generators/syntax.rb symbol > etc/examples/syntax/symbol.rb`

  :'
    foo
    \'
    \\\'
    bar
  '



  ]:'
    foo
    \'
    \\\'
    bar
  '



  }:'
    foo
    \'
    \\\'
    bar
  '



  ):'
    foo
    \'
    \\\'
    bar
  '



  ":'
    foo
    \'
    \\\'
    bar
  '
  " # close string to ensure next case clean


  ':'
    foo
    \'
    \\\'
    bar
  '



  ::'
    foo
    \'
    \\\'
    bar
  '



  :"
    foo
    \"
    \\\"
    bar
  "



  ]:"
    foo
    \"
    \\\"
    bar
  "



  }:"
    foo
    \"
    \\\"
    bar
  "



  ):"
    foo
    \"
    \\\"
    bar
  "



  ":"
    foo
    \"
    \\\"
    bar
  "



  ':"
    foo
    \"
    \\\"
    bar
  "
  ' # close string to ensure next case clean


  ::"
    foo
    \"
    \\\"
    bar
  "



# vim:foldmethod=syntax
